/*
 * Copyright 2020 Hector Espert.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package es.blackleg.nb.notifications.core.center;

import java.util.Properties;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.windows.TopComponent;

/**
 *
 * @author Hector Espert
 */
//@ConvertAsProperties(
//        dtd = "-//es.blackleg.nb.notifications.core.center//NotificationCenter//EN",
//        autostore = false)
//@TopComponent.Description(
//        preferredID = "NativeNotificationCenter",
//        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
//@TopComponent.Registration(mode = "output", openAtStartup = false, position = 123)
public class NativeNotificationCenter extends TopComponent {

    /**
     * Creates new form NativeNotificationCenter
     */
    public NativeNotificationCenter() {
        initComponents();
    }

    void writeProperties(Properties p) {

    }

    void readProperties(Properties p) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
